// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWOoXN5pTt_4lCFv7f1pBMCGecOEf4u8',
    appId: '1:974802735275:web:ac2092f0455978140667ee',
    messagingSenderId: '974802735275',
    projectId: 'project-ott-ec78e',
    authDomain: 'project-ott-ec78e.firebaseapp.com',
    storageBucket: 'project-ott-ec78e.appspot.com',
    measurementId: 'G-TJK1JTHQ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBup_CWELq91Sh8IhiU3dQGRWNBTKPTVsw',
    appId: '1:974802735275:android:5044adc9830c79f90667ee',
    messagingSenderId: '974802735275',
    projectId: 'project-ott-ec78e',
    storageBucket: 'project-ott-ec78e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdya1zqYgJj25n7ecOHJqxGqtIuOlK8gM',
    appId: '1:974802735275:ios:066a714e735022610667ee',
    messagingSenderId: '974802735275',
    projectId: 'project-ott-ec78e',
    storageBucket: 'project-ott-ec78e.appspot.com',
    iosBundleId: 'com.example.ott',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdya1zqYgJj25n7ecOHJqxGqtIuOlK8gM',
    appId: '1:974802735275:ios:066a714e735022610667ee',
    messagingSenderId: '974802735275',
    projectId: 'project-ott-ec78e',
    storageBucket: 'project-ott-ec78e.appspot.com',
    iosBundleId: 'com.example.ott',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEWOoXN5pTt_4lCFv7f1pBMCGecOEf4u8',
    appId: '1:974802735275:web:418f1577777cfdc50667ee',
    messagingSenderId: '974802735275',
    projectId: 'project-ott-ec78e',
    authDomain: 'project-ott-ec78e.firebaseapp.com',
    storageBucket: 'project-ott-ec78e.appspot.com',
    measurementId: 'G-Y7NE1QE9K8',
  );
}
